const {chromium}=require(require('path').join(process.env.TEMP,'pick-play-browser-tests/node_modules/playwright'));
const assert=require('node:assert/strict');
const {deflateRawSync}=require('node:zlib');
function makeCbz(entries){
 const locals=[],centrals=[];let offset=0;
 for(const [name,data] of entries){const n=Buffer.from(name),raw=Buffer.from(data),d=deflateRawSync(raw),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(8,8);local.writeUInt32LE(d.length,18);local.writeUInt32LE(raw.length,22);local.writeUInt16LE(n.length,26);locals.push(local,n,d);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(8,10);central.writeUInt32LE(d.length,20);central.writeUInt32LE(raw.length,24);central.writeUInt16LE(n.length,28);central.writeUInt32LE(offset,42);centrals.push(central,n);offset+=local.length+n.length+d.length;}
 const centralSize=centrals.reduce((sum,b)=>sum+b.length,0),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,...centrals,end]);
}
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:4180');await page.evaluate(()=>localStorage.clear());await page.reload();
 assert.equal(await page.locator('.app-card').count(),3);
 await page.locator('#theme-toggle').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('#theme-toggle').getAttribute('aria-pressed'),'true');await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.locator('#theme-toggle').click();
 await page.locator('.books-card').click();await page.locator('#new-book').click();await page.locator('#book-title').fill('Test story');assert.equal(await page.locator('#book-text').getAttribute('maxlength'),'1200');await page.locator('#book-text').fill('Once upon a time.\nA new chapter.');await page.locator('#add-page').click();await page.locator('#book-text').fill('x'.repeat(1300));assert.equal((await page.locator('#book-text').inputValue()).length,1200);await page.locator('#book-text').fill('This is the second paper page.');assert.match(await page.locator('#edit-page-footer').innerText(),/2 \/ 2/);await page.locator('#save-book').click();await page.reload();
 assert.match(await page.locator('#shelf').innerText(),/Test story/);
 await page.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#book-title').fill('Edited story');await page.locator('#save-book').click();await page.locator('#read-book').click();assert.equal(await page.locator('#read-title').innerText(),'Edited story');assert.match(await page.locator('#read-text').innerText(),/Once upon/);assert.match(await page.locator('#read-page-count').innerText(),/Page 1 of 2/);await page.locator('#read-next-page').click();assert.match(await page.locator('#read-text').innerText(),/second paper page/);await page.locator('#close-reader').click();
 const downloadPromise=page.waitForEvent('download');await page.locator('#export-books').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/haven-books/);
 await page.getByRole('button',{name:'Delete',exact:true}).click();assert.equal(await page.locator('.shelf-card').count(),0);
 await page.locator('#import-books').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,books:[{id:'a',title:'Imported',description:'',text:'Words',color:'#697961'}]}))});assert.equal(await page.locator('.shelf-card').count(),1);
 await page.locator('nav a[href="#manga"]').click();
 await page.evaluate(()=>{
  const input=document.getElementById('manga-files');const transfer=new DataTransfer();
  for(const path of ['Library/Book 10/1.png','Library/Book 2/10.png','Library/Book 2/2.png']){const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg=='),c=>c.charCodeAt(0));const file=new File([bytes],path.split('/').pop(),{type:'image/png'});Object.defineProperty(file,'webkitRelativePath',{value:path});transfer.items.add(file);}input.files=transfer.files;input.dispatchEvent(new Event('change'));
 });
 assert.deepEqual(await page.locator('#manga-book option').allTextContents(),['Library/Book 2','Library/Book 10']);
 await page.locator('#reading-mode').selectOption('swipe');await page.locator('#next-page').click();assert.match(await page.locator('#page-info').innerText(),/Page 2 of 2/);await page.locator('#next-page').click();assert.match(await page.locator('#page-info').innerText(),/Book 10/);
 await page.locator('#manga-book').selectOption('0');await page.locator('#pace').fill('200');await page.locator('#auto-scroll').click();await page.waitForFunction(()=>document.getElementById('manga-book').value==='1',{},{timeout:10000});
 await page.locator('#reader-width').fill('700');await page.locator('#reader-height').fill('600');assert.equal(await page.locator('#manga-stage').evaluate(el=>[el.style.width,el.style.height].join('x')),'700pxx600px');await page.locator('#manga-cbz-folder').click();await page.locator('#folder-path').waitFor();assert.equal(await page.locator('#folder-modal').isVisible(),true);await page.locator('#folder-close').click();
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
 await page.locator('#manga-cbz').setInputFiles([{name:'Volume 10.cbz',mimeType:'application/zip',buffer:makeCbz([['10.png',png],['2.png',png]])},{name:'Volume 2.cbz',mimeType:'application/zip',buffer:makeCbz([['1.png',png]])}]);
 await page.waitForFunction(()=>document.querySelectorAll('#manga-book option').length===2);assert.deepEqual(await page.locator('#manga-book option').allTextContents(),['Volume 2','Volume 10']);await page.locator('#manga-book').selectOption('1');assert.match(await page.locator('#page-info').innerText(),/Page 1 of 2/);
 await page.locator('nav a[href="#anime"]').click();
 // Build a short, valid video with the browser's own encoder.
 const bytes=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=64;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle='green';ctx.fillRect(0,0,64,64);const stream=canvas.captureStream(10);const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];const done=new Promise(resolve=>recorder.onstop=async()=>resolve(Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer()))));recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();await new Promise(r=>setTimeout(r,600));recorder.stop();stream.getTracks().forEach(t=>t.stop());return done;});
 await page.locator('#video-files').setInputFiles([{name:'Episode 10.webm',mimeType:'video/webm',buffer:Buffer.from(bytes)},{name:'Episode 2.webm',mimeType:'video/webm',buffer:Buffer.from(bytes)}]);
 assert.equal(await page.locator('#video-title').innerText(),'Episode 2.webm');await page.locator('#video-speed').selectOption('1.5');assert.equal(await page.locator('#video').evaluate(v=>v.playbackRate),1.5);await page.locator('#loop-series').check();await page.locator('#replay').click();await page.waitForFunction(()=>document.getElementById('video-title').textContent==='Episode 10.webm');await page.waitForFunction(()=>document.getElementById('video-title').textContent==='Episode 2.webm');
 const mpvStatus=await page.evaluate(()=>fetch('/api/mpv/status').then(r=>r.json()));assert.equal(mpvStatus.available,true);assert.equal(await page.locator('#open-mpv-folder').innerText(),'Choose anime folder');await page.locator('#open-mpv-folder').click();await page.waitForFunction(()=>document.querySelectorAll('#folder-list button').length>0);assert.equal(await page.locator('#folder-modal').isVisible(),true);assert.ok(await page.locator('#folder-list button').count()>0);await page.locator('#folder-close').click();
 await page.locator('nav a[href="#home"]').click();await page.screenshot({path:'apps-site/desktop-preview.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'apps-site/mobile-preview.png',fullPage:true});
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: paged book writing/reading/persistence, backup export/import, full-size image-folder and CBZ manga reading, browser series loop, anime-folder MPV bridge, mobile width; no browser errors.');
})().catch(e=>{console.error(e);process.exit(1);});
