const presets={games:['Minecraft','Mario Kart 8','Fortnite','Stardew Valley','Overcooked 2'],anime:['Attack on Titan','One Piece','Jujutsu Kaisen','Spy x Family','Frieren'],movies:['The Matrix','Spirited Away','Knives Out','The Grand Budapest Hotel','Everything Everywhere All at Once']};
let items=[];let mode='jar';let players=2;let round=0;let history=[];const $=id=>document.getElementById(id);const modeNames={jar:'Draw from a jar',wheel:'Spin the wheel',dice:'Roll the dice',coin:'Flip a coin',rps:'Rock paper scissors',number:'Guess the number',checkers:'Checkers',tictactoe:'Tic-Tac-Toe'};
function renderItems(){ $('itemCount').textContent=`${items.length} item${items.length===1?'':'s'}`; $('items').innerHTML=items.length?items.map((item,i)=>`<div class="item"><span><span class="item-index">${String(i+1).padStart(2,'0')}</span>${escapeHtml(item)}</span><button class="remove" data-index="${i}" aria-label="Remove ${escapeHtml(item)}">×</button></div>`).join(''):'<div class="empty-items">Your list is empty.<br/>Add a few options or choose a quick start.</div>';document.querySelectorAll('.remove').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.index,1);renderItems();save()})}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addItem(){const input=$('itemInput');const value=input.value.trim();if(!value)return;if(!items.some(x=>x.toLowerCase()===value.toLowerCase()))items.push(value);input.value='';renderItems();save()}
function save(){localStorage.setItem('pick-play-state',JSON.stringify({items,players,history}))}
function pick(arr){return arr[Math.floor(Math.random()*arr.length)]}
function play(){if(mode==='jar'||mode==='wheel'){if(items.length<2){show('Add at least 2 options','A little more variety makes the result more fun.','＋');return}const result=pick(items);show(result,mode==='jar'?'The jar chose for you':'The wheel landed on','✦');if(mode==='wheel')$('resultStage').classList.add('spinning');setTimeout(()=>$('resultStage').classList.remove('spinning'),600);addHistory(result,modeNames[mode])}else if(mode==='dice'){const rolls=Array.from({length:players},()=>Math.floor(Math.random()*6)+1);const high=Math.max(...rolls);const winner=rolls.indexOf(high)+1;show(`Player ${winner} wins`,`Rolled ${rolls.join(' · ')} — highest roll`,`⚄`);addHistory(`Player ${winner} (${high})`,'Dice roll')}else if(mode==='coin'){const result=Math.random()<.5?'Heads':'Tails';show(result,'The coin says','◐');addHistory(result,'Coin flip')}else if(mode==='rps'){const choices=[['Rock','✊'],['Paper','✋'],['Scissors','✌']];const a=pick(choices),b=pick(choices);show(`${a[1]} ${a[0]}`,`Player 1 vs Player 2 · ${b[1]} ${b[0]}`,'✌');addHistory(`${a[0]} vs ${b[0]}`,'Rock paper scissors')}else{const number=Math.floor(Math.random()*100)+1;show(number,'Your mystery number is','?');addHistory(number,'Number guess')}round++;$('roundText').textContent=`ROUND ${String(round).padStart(2,'0')}`}
function show(title,kicker,icon){$('resultTitle').innerHTML=String(title).includes(' ')&&String(title).length>21?String(title).replace(' ','<br/>'):title;$('resultKicker').textContent=kicker;const playerModes=['dice','rps','number','checkers','tictactoe'];$('resultSub').textContent=mode==='jar'||mode==='wheel'?'Item selected from your list.':playerModes.includes(mode)?'Winner gets first pick from your list.':'A random side was chosen.';$('resultSymbol').textContent=icon;$('stageMode').textContent=modeNames[mode].toUpperCase();$('playText').textContent=modeNames[mode]}
function addHistory(result,label){history.unshift({result,label});history=history.slice(0,5);$('historyList').innerHTML=history.map(h=>`<div class="history-item"><strong>${escapeHtml(String(h.result))}<small>${escapeHtml(h.label)}</small></strong><span>just now</span></div>`).join('');save()}
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=b.dataset.preset;if(p==='clear')items=[];else items=[...presets[p]];renderItems();save()});$('addBtn').onclick=addItem;$('itemInput').addEventListener('keydown',e=>{if(e.key==='Enter')addItem()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode-card').forEach(x=>x.classList.toggle('active',x===b));show('Ready to play','Your result will land here','?');$('turnLabel').textContent=modeNames[mode]});$('playBtn').onclick=play;$('minusPlayers').onclick=()=>{players=Math.max(2,players-1);$('playerCount').textContent=players;save()};$('plusPlayers').onclick=()=>{players=Math.min(4,players+1);$('playerCount').textContent=players;save()};$('clearHistory').onclick=()=>{history=[];$('historyList').innerHTML='<p class="empty-history">Your plays will show up here.</p>';save()};
const originalPlay=play;play=function(){if(mode==='tictactoe'){const symbol=pick(['X','O']);const starter=symbol==='X'?'Player 1':'Player 2';show(`${symbol} starts`,`${starter} goes first`,'✕');addHistory(`${symbol} starts`,'Tic-Tac-Toe');round++;$('roundText').textContent=`ROUND ${String(round).padStart(2,'0')}`;return}originalPlay()};$('playBtn').onclick=play;
try{const saved=JSON.parse(localStorage.getItem('pick-play-state'));if(saved){items=saved.items||[];players=saved.players||2;history=saved.history||[];$('playerCount').textContent=players;if(history.length)$('historyList').innerHTML=history.map(h=>`<div class="history-item"><strong>${escapeHtml(String(h.result))}<small>${escapeHtml(h.label)}</small></strong><span>previously</span></div>`).join('')}}catch(e){}renderItems();
