let savedLists=[];let currentListIndex=0;
function persistLists(){if(!savedLists.length)savedLists=[{name:'My list',items:[]}];savedLists[currentListIndex].items=[...items];savedLists.forEach(list=>{if(!list.localId)list.localId=crypto.randomUUID()});localStorage.setItem('pick-play-lists',JSON.stringify(savedLists));localStorage.setItem('pick-play-current',String(currentListIndex));localStorage.setItem('pick-play-state',JSON.stringify({items,players,history}));window.dispatchEvent(new Event('pickplay-lists-changed'))}
function renderSavedLists(){const select=document.getElementById('listSelect');if(!select)return;select.innerHTML=savedLists.map((list,index)=>`<option value="${index}">${escapeHtml(list.name)} · ${list.items.length} item${list.items.length===1?'':'s'}</option>`).join('');select.value=String(currentListIndex);document.getElementById('listNameInput').value=savedLists[currentListIndex].name}
const originalSave=save;save=function(){persistLists()};
try{const old=JSON.parse(localStorage.getItem('pick-play-state')||'null');const stored=JSON.parse(localStorage.getItem('pick-play-lists')||'null');if(Array.isArray(stored)&&stored.length){savedLists=stored;currentListIndex=Math.min(Number(localStorage.getItem('pick-play-current')||0),savedLists.length-1);items=[...savedLists[currentListIndex].items]}else{savedLists=[{name:'My list',items:[...(old?.items||items)]}];currentListIndex=0;items=[...savedLists[0].items]}}catch(e){savedLists=[{name:'My list',items:[...items]}]}
renderItems();renderSavedLists();
document.getElementById('listSelect').onchange=e=>{persistLists();currentListIndex=Number(e.target.value);items=[...savedLists[currentListIndex].items];renderItems();renderSavedLists();persistLists()};
document.getElementById('listNameInput').addEventListener('input',()=>{savedLists[currentListIndex].name=document.getElementById('listNameInput').value.trim()||`List ${currentListIndex+1}`;persistLists()});
document.getElementById('newListBtn').onclick=()=>{persistLists();let number=savedLists.length+1;let name=`New list ${number}`;while(savedLists.some(list=>list.name===name)){number++;name=`New list ${number}`}savedLists.push({name,items:[]});currentListIndex=savedLists.length-1;items=[];renderItems();renderSavedLists();persistLists();document.getElementById('listNameInput').focus()};
